apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sistema-noticias-statefulset
spec:
  replicas: 3
  template:
    metadata:
      name: sistema-noticias
      labels:
        app: sistema-noticias
    spec:
      containers:
        - name: sistema-noticias-container
          image: aluracursos/sistema-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: sistema-configmap
          volumeMounts:
            - name: imagens
              mountPath: /var/www/html/uploads
            - name: sessao
              mountPath: /tmp
          livenessProbe: # usado para validar o teste abaixo 
            httpGet:
              path: /
              port: 80
            periodSeconds: 10 # intervalor em segundos para executar o teste
            failureThreshold: 3 # significa se não conseguir fazer o teste na proxima ele reinicia o pod e desabilita para novas requisicoes
            initialDelaySeconds: 30 #apos subida inicia o teste depois de 20 segundos
          readinessProbe: # usado para definir quando o pod podera receber novas requisicoes do service
            httpGet:
              path: /
              port: 80
            periodSeconds: 10 # intervalo em segundos para executar o teste
            failureThreshold: 3 #significa se não conseguir o teste na proxima ele ignora o readinessprobe e habilita o pod a receber requisicoes
            initialDelaySeconds: 30 #apos subida inicia o teste depois de 20 segundos            
      volumes:
        - name: imagens
          persistentVolumeClaim:
            claimName: pvc-imagens      
        - name: sessao
          persistentVolumeClaim:
            claimName: pvc-sessao
  selector:
    matchLabels:
      app: sistema-noticias
  serviceName: svc-sistema-noticias
  